// tests/bake/helpers.ts — shared fixtures for the WP7 baker tests: world / hand-built neighbourhoods, surfaces,
// half decoding and FILTERED (bilinear) lightmap sampling on the floor grid chart.

import { CELL, CHUNK_CELL_COUNT, STD_CEIL_CM, type LmTpc } from '../../src/core/constants.ts';
import { exIdx, ezIdx, type ChunkKey, type TileKey } from '../../src/core/grid.ts';
import { fromHalf } from '../../src/core/half.ts';
import { CeilKind, CellFlag, EdgeKind, FixtureKind, LightState, Mat, Mood, Zone, type LandmarkKindId, type StoreyId, type ZoneId } from '../../src/core/ids.ts';
import { createEmptyLayout, fixtureSeed, type ChunkLayout, type Fixture } from '../../src/core/layout.ts';
import { ChartKind, type Chart, type LightmapData, type SurfaceSet } from '../../src/core/mesh.ts';
import type { BakeQuality } from '../../src/core/quality.ts';
import type { LayoutNeighborhood, WorldGenOptions } from '../../src/core/world.ts';
import { chartHash } from '../../src/mesh/chartHash.ts';
import { buildTileSurfaces } from '../../src/mesh/surfaces.ts';
import { labelRooms } from '../../src/world/rooms.ts';
import { makeNeighborhood } from '../../src/world/neighborhood.ts';
import { createWorldGen } from '../../src/world/worldgen.ts';

export const Q_HIGH: BakeQuality = { tpc: 12, shadowSamples: 4, probeRays: 96 };
export const Q_LOW: BakeQuality = { tpc: 8, shadowSamples: 1, probeRays: 32 };
export const qFor = (tpc: LmTpc): BakeQuality => (tpc === 12 ? Q_HIGH : { tpc: 8, shadowSamples: 2, probeRays: 64 });

export function worldOpts(p: Partial<WorldGenOptions> = {}): WorldGenOptions {
  return { seed: 1, seedText: '1', forceZone: null, forceMood: null, forceLandmark: null, testScene: null, lights: 'default', ...p };
}

/** 3x3 neighbourhood around chunk (s, cx, cz) generated by the real world generator. */
export function worldNeighborhood(opts: WorldGenOptions, s: StoreyId, cx: number, cz: number): LayoutNeighborhood {
  const gen = createWorldGen(opts);
  const ls: ChunkLayout[] = [];
  for (let dz = -1; dz <= 1; dz++) for (let dx = -1; dx <= 1; dx++) ls.push(gen.generateChunk({ s, cx: cx + dx, cz: cz + dz }));
  return makeNeighborhood(ls);
}

export function zoneNeighborhood(zone: ZoneId, cx = 0, cz = 0, s: StoreyId = 0, extra: Partial<WorldGenOptions> = {}): LayoutNeighborhood {
  return worldNeighborhood(worldOpts({ forceZone: zone, lights: 'on', ...extra }), s, cx, cz);
}
export function landmarkNeighborhood(lm: LandmarkKindId, s: StoreyId = 0): LayoutNeighborhood {
  return worldNeighborhood(worldOpts({ forceLandmark: lm, lights: 'on' }), s, 0, 0);
}

export const surfacesOf = (nb: LayoutNeighborhood, tile: TileKey, tpc: LmTpc): SurfaceSet => buildTileSurfaces(nb, tile, tpc);

// ---------------------------------------------------------------- hand-built layouts

/** A solid chunk (every cell SOLID) with standard materials. */
export function solidLayout(key: ChunkKey): ChunkLayout {
  const l = createEmptyLayout(key, Zone.LOBBY, 0, Mood.NORMAL);
  l.flags.fill(CellFlag.SOLID);
  l.ceilCm.fill(STD_CEIL_CM);
  l.floorMat.fill(Mat.CARPET_L0); l.ceilMat.fill(Mat.CEILING_TILE); l.ceilKind.fill(CeilKind.TILES);
  l.wallMat.fill(Mat.WALLPAPER_L0);
  for (const e of [l.ex, l.ez]) { e.matNeg.fill(Mat.WALLPAPER_L0); e.matPos.fill(Mat.WALLPAPER_L0); }
  return l;
}

/** Open floor cells [i0,i1) x [j0,j1) enclosed by edges of `kind` (hA default for the kind). */
export function carveRoom(l: ChunkLayout, i0: number, j0: number, i1: number, j1: number, ceilCm = STD_CEIL_CM, kind: number = EdgeKind.WALL, hA = 0): void {
  for (let j = j0; j < j1; j++) {
    for (let i = i0; i < i1; i++) {
      const c = j * 32 + i;
      l.flags[c] = 0; l.floorCm[c] = 0; l.ceilCm[c] = ceilCm;
      l.power[c] = 220; l.decay[c] = 40; l.humidity[c] = 60; l.warmth[c] = 128;
    }
  }
  for (let j = j0; j < j1; j++) { setEx(l, i0, j, kind, hA); setEx(l, i1, j, kind, hA); }
  for (let i = i0; i < i1; i++) { setEz(l, i, j0, kind, hA); setEz(l, i, j1, kind, hA); }
}
export function setEx(l: ChunkLayout, i: number, j: number, kind: number, hA = 0, hB = 0): void {
  const e = exIdx(i, j);
  l.ex.kind[e] = kind; l.ex.hA[e] = hA; l.ex.hB[e] = hB;
}
export function setEz(l: ChunkLayout, i: number, j: number, kind: number, hA = 0, hB = 0): void {
  const e = ezIdx(i, j);
  l.ez.kind[e] = kind; l.ez.hA[e] = hA; l.ez.hB[e] = hB;
}

let fid = 1;
/** A static light fixture (chunk-local metres). Recessed troffer by default. */
export function addLight(l: ChunkLayout, p: Partial<Fixture> & { px: number; pz: number }): Fixture {
  const id = p.id ?? (fid++ * 7919);
  const f: Fixture = {
    id, kind: FixtureKind.TROFFER_2x4, state: LightState.ON, shape: 0,
    py: 2.7, nx: 0, ny: -1, nz: 0, tx: 1, ty: 0, tz: 0, w: 1.2, h: 0.6, color: [1, 1, 1], luminance: 3300,
    seed: fixtureSeed(id), hum: 0.5, bakeGroup: 0, dynamic: false, ...p,
  };
  l.fixtures.push(f);
  return f;
}

/** Finish a hand layout (room labels) and wrap it with 8 solid neighbours. */
export function handNeighborhood(center: ChunkLayout, neighbours?: (key: ChunkKey) => ChunkLayout): LayoutNeighborhood {
  labelRooms(center);
  const ls: ChunkLayout[] = [];
  for (let dz = -1; dz <= 1; dz++) {
    for (let dx = -1; dx <= 1; dx++) {
      if (dx === 0 && dz === 0) { ls.push(center); continue; }
      const key = { s: center.key.s, cx: center.key.cx + dx, cz: center.key.cz + dz };
      const l = neighbours ? neighbours(key) : solidLayout(key);
      labelRooms(l);
      ls.push(l);
    }
  }
  return makeNeighborhood(ls);
}

export function emptyLayout(key: ChunkKey): ChunkLayout {
  const l = solidLayout(key);
  void CHUNK_CELL_COUNT;
  return l;
}

/** Grid-chart-only SurfaceSet (floor + ceiling grids of the tile): independent of the mesher. */
export function gridSurfaces(tile: TileKey, tpc: LmTpc): SurfaceSet {
  const t = CELL / tpc;
  const side = 16 * tpc + 2;
  const charts: Chart[] = [];
  const mk = (id: number, kind: 0 | 1, x: number, y: number): Chart => ({
    id, kind, bakeGroup: 0, x, y, w: side, h: side,
    origin: [-t, kind === ChartKind.FLOOR_GRID ? 0 : 2.7, -t], axisU: [t, 0, 0], axisV: [0, 0, t],
    normal: kind === ChartKind.FLOOR_GRID ? [0, 1, 0] : [0, -1, 0], layer: kind === 0 ? Mat.CARPET_L0 : Mat.CEILING_TILE, cont: 15,
  });
  charts.push(mk(0, 0, 2, 2));
  charts.push(mk(1, 1, 2, 2 + side + 4));
  const atlasH = 2 + 2 * side + 8 <= 512 ? 512 : 1024;
  return { tileKey: `${tile.s}:${tile.cx}:${tile.cz}:${tile.q}`, tpc, atlasW: 512, atlasH, charts, hash: chartHash(charts) };
}

// ---------------------------------------------------------------- decoding / sampling

export const findChart = (s: SurfaceSet, kind: number, group = 0): Chart => {
  const c = s.charts.find((ch) => ch.kind === kind && ch.bakeGroup === group);
  if (!c) throw new Error(`no chart of kind ${kind}`);
  return c;
};

/** Raw irradiance luminance at an atlas texel. */
export function texelLum(lm: LightmapData, ax: number, ay: number, arr: 'irr' | 'flick' = 'irr', ch = -1): number {
  const o = (ay * lm.width + ax) * 4;
  if (arr === 'flick') {
    if (!lm.flick) return 0;
    if (ch >= 0) return fromHalf(lm.flick[o + ch]);
    return fromHalf(lm.flick[o]) + fromHalf(lm.flick[o + 1]) + fromHalf(lm.flick[o + 2]) + fromHalf(lm.flick[o + 3]);
  }
  return 0.2126 * fromHalf(lm.irr[o]) + 0.7152 * fromHalf(lm.irr[o + 1]) + 0.0722 * fromHalf(lm.irr[o + 2]);
}
export function texelRGB(lm: LightmapData, ax: number, ay: number): [number, number, number] {
  const o = (ay * lm.width + ax) * 4;
  return [fromHalf(lm.irr[o]), fromHalf(lm.irr[o + 1]), fromHalf(lm.irr[o + 2])];
}

/**
 * BILINEARLY FILTERED luminance of a grid chart at tile-local (x, z) metres, exactly as the GPU samples it
 * (texel centres at atlas (i + 0.5)).
 */
export function sampleGrid(lm: LightmapData, chart: Chart, tpc: LmTpc, x: number, z: number, arr: 'irr' | 'flick' = 'irr'): number {
  const t = CELL / tpc;
  // texel u centre at x = (u - 0.5) t  =>  continuous atlas coordinate (texel-centre aligned)
  const fu = chart.x + x / t + 0.5, fv = chart.y + z / t + 0.5;
  const u0 = Math.floor(fu), v0 = Math.floor(fv);
  const au = fu - u0, av = fv - v0;
  let s = 0;
  for (let b = 0; b < 2; b++) for (let a = 0; a < 2; a++) {
    const w = (a ? au : 1 - au) * (b ? av : 1 - av);
    if (w === 0) continue;
    s += w * texelLum(lm, u0 + a, v0 + b, arr);
  }
  return s;
}

/** Atlas texel of a grid chart containing tile-local (x, z). */
export function gridTexel(chart: Chart, tpc: LmTpc, x: number, z: number): [number, number] {
  const t = CELL / tpc;
  return [chart.x + Math.floor(x / t + 1), chart.y + Math.floor(z / t + 1)];
}
