// src/materials/chunks/detail.ts — package B: LEAN detail maps (uBrDetail: 11 + 1 layers of 512^2 RGBA8 over a 0.3 m
// world repeat, textures/detail.ts; generated by textures/DetailBaker.ts only when QualityConfig.detailMaps). The
// uBrDetail / uBrLayerD uniforms are declared in chunks/common.ts; the shading code sits in chunks/surface.ts
// (FRAG_MAP_GLSL detail block, the ripple in the wetness block, the LEAN term in FRAG_ROUGHNESS_GLSL and the second
// cotangent frame in FRAG_NORMAL_GLSL), all under BR_DETAIL_MAPS (high / ultra) and never in the decal variant.
// Texture realism v2 detail controls: the repeat scale BR_L_DETREP, the 'detailMask' strength and the tint
// BR_L_DETTINT sit in FRAG_MAP_GLSL; the detail cavity's share of the specular occlusion (BR_L_DETSO) is
// FRAG_DETAIL_SO_GLSL below.

/** Appended to the fragment common block. */
export const DETAIL_PARS_GLSL = /* glsl */ `
// ---- detail maps (package B)
#if defined( BR_DETAIL_MAPS ) && ! defined( BR_DECAL )
// LEAN detail texel (rg = mean slope / S, b = albedo multiplier / 2, a = E[slope^2] / 2S^2) at the detail-uv footprint
// (dx, dy), faded to the layer mean mu (the 1x1 mip, a constant address) between BR_DETAIL_FAR0 and BR_DETAIL_FAR1
// detail texels per pixel; the filtered fetch is skipped beyond. The moments mix linearly, so a faded texel is still
// a valid LEAN sample: far away the detail survives as its slope variance (micro-roughness), never as a fade band.
vec4 brDetailFetch( vec2 uv, float layer, vec2 dx, vec2 dy, out vec4 mu ) {
	mu = textureLod( uBrDetail, vec3( 0.5, 0.5, layer ), 16.0 );
	float near = 1.0 - smoothstep( BR_DETAIL_FAR0, BR_DETAIL_FAR1, max( length( dx ), length( dy ) ) * BR_DETAIL_RES );
	vec4 t = mu;
	if ( near > 0.0 ) t = mix( mu, textureGrad( uBrDetail, vec3( uv, layer ), dx, dy ), near );
	return t;
}
#endif
`;

/** After FRAG_AO_REFL_GLSL (aomap_fragment), before the family postLight hooks: the detail cavity (brAm < 1 in the
 * detail layer's pits, pile gaps and pores) occludes the environment specular by the layer's share BR_L_DETSO (0 =
 * off), at most halving it. Routed base-lobe reflections take the same attenuation on their environment fallback
 * and SSR weight; the baked directional lobe and the separate lacquer lobe keep their own visibility. */
export const FRAG_DETAIL_SO_GLSL = /* glsl */ `
#if defined( BR_DETAIL_MAPS ) && ! defined( BR_DECAL )
// ---- detail specular occlusion (texture realism v2)
if ( BR_L_DETSO[ brL ] > 0.0 ) {
	float brDso = max( 0.5, mix( 1.0, brAm, 0.5 * brDetL.y * BR_L_DETSO[ brL ] ) );
	reflectedLight.indirectSpecular *= brDso;
#ifdef BR_SSR
	if ( brMrtSpec && ! brCoat ) {
		brFbSpec = mix( brFbDir, brFbSpec, brDso );
		brWs *= brDso;
		brWsRgb *= brDso;
	}
#endif
}
#endif
`;
