// src/textures/DetailBaker.ts — GPU generation of the LEAN detail-map array (package B; recipes in detail.ts).
//
// One WebGLArrayRenderTarget of DETAIL_COUNT layers, DETAIL_SIZE^2 RGBA8 (NoColorSpace: packed data), trilinear +
// anisotropic, repeat wrap. Per layer: HEIGHT -> the shared height scratch, then the pack pass (glsl/common.ts
// DETAIL_MAIN: rg mean slope, b albedo multiplier, a mean squared slope) -> array layer. The box-filtered mip chain
// (generated by the last draw) keeps the first and second slope moments exact, which is what the shader's LEAN
// variance needs. Programs compile in parallel (compileAsync). Generated only when QualityConfig.detailMaps is on
// (app/boot.ts, lazily on a quality switch); ~15 MiB of VRAM.

import * as THREE from 'three';
import { DETAIL_COUNT, DETAIL_RECIPES, DETAIL_REPEAT, DETAIL_SIZE } from './detail.ts';
import { buildDetailFragment, OUT_ALBEDO, OUT_HEIGHT } from './glsl/common.ts';
import { createBlitter, createHeightScratch, rawMaterial } from './programs.ts';

export interface DetailBakeStats {
  compileMs: number;
  genMs: number;
  totalMs: number;
}

let lastStats: DetailBakeStats | null = null;
/** Timings of the most recent generateDetailTextures call (null before the first). */
export function detailBakeStats(): DetailBakeStats | null { return lastStats; }

/** Generate the detail array (uBrDetail). Disposing the returned texture frees its render target. */
export async function generateDetailTextures(renderer: THREE.WebGLRenderer, anisotropy: number): Promise<THREE.Texture> {
  const t0 = performance.now();
  const S = DETAIL_SIZE;
  const rt = new THREE.WebGLArrayRenderTarget(S, S, DETAIL_COUNT, {
    type: THREE.UnsignedByteType,
    format: THREE.RGBAFormat,
    colorSpace: THREE.NoColorSpace,
    depthBuffer: false,
    stencilBuffer: false,
    generateMipmaps: false,
    minFilter: THREE.LinearMipmapLinearFilter,
    magFilter: THREE.LinearFilter,
    wrapS: THREE.RepeatWrapping,
    wrapT: THREE.RepeatWrapping,
    anisotropy,
  });
  rt.texture.name = 'br-detail';
  const blit = createBlitter(renderer);
  const { scratch, packed } = createHeightScratch(renderer, S);
  const dummy = new THREE.DataTexture(new Uint8Array([128, 0, 0, 255]), 1, 1);
  dummy.needsUpdate = true;

  // shared uniform objects (same object in every recipe material)
  const uOut = { value: OUT_HEIGHT };
  const uScratch: THREE.IUniform<THREE.Texture> = { value: dummy };
  const uHPackOut = { value: 0 };
  const common = { uOut, uScratch, uHPackOut, uRes: { value: S }, uOrigin: { value: new THREE.Vector2() }, uHPackIn: { value: packed ? 1 : 0 } };
  const mats = DETAIL_RECIPES.map((r, i) => {
    const m = rawMaterial(buildDetailFragment({ layer: i, repeat: DETAIL_REPEAT, slope: r.slope, cavity: r.cavity }, r.glsl),
      { ...common, uHeightM: { value: r.heightScale } });
    m.name = `br-detail-${r.name}`;
    return m;
  });

  const prevTarget = renderer.getRenderTarget();
  const prevAutoClear = renderer.autoClear;
  renderer.autoClear = false;
  let compileMs = 0;
  let genMs = 0;
  try {
    const scene = new THREE.Scene();
    for (const m of mats) {
      const mesh = new THREE.Mesh(blit.geometry, m);
      mesh.frustumCulled = false;
      scene.add(mesh);
    }
    renderer.setRenderTarget(scratch); // compile with a render target bound, as drawn
    const tc = performance.now();
    await renderer.compileAsync(scene, blit.camera);
    compileMs = performance.now() - tc;

    const tg = performance.now();
    for (let L = 0; L < DETAIL_COUNT; L++) {
      uOut.value = OUT_HEIGHT;
      uScratch.value = dummy; // never sample the scratch while it is the render target
      uHPackOut.value = packed ? 1 : 0;
      blit.draw(mats[L], scratch);
      uOut.value = OUT_ALBEDO; // the pack pass
      uScratch.value = scratch.texture;
      uHPackOut.value = 0;
      if (L === DETAIL_COUNT - 1) rt.texture.generateMipmaps = true; // the final draw generates the whole mip chain
      blit.draw(mats[L], rt, L);
    }
    renderer.setRenderTarget(null);
    const probe = new Uint8Array(4);
    await renderer.readRenderTargetPixelsAsync(rt, 0, 0, 1, 1, probe); // wait for the GPU (the last layer is attached)
    genMs = performance.now() - tg;
  } catch (e) {
    rt.dispose();
    throw e;
  } finally {
    renderer.setRenderTarget(prevTarget);
    renderer.autoClear = prevAutoClear;
    for (const m of mats) m.dispose();
    scratch.dispose();
    dummy.dispose();
    blit.dispose();
  }
  const tex = rt.texture;
  tex.addEventListener('dispose', () => rt.dispose());
  lastStats = { compileMs, genMs, totalMs: performance.now() - t0 };
  console.info(`[textures] detail compileMs=${compileMs.toFixed(0)} genMs=${genMs.toFixed(0)}`);
  return tex;
}
